# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8208e1ff2512d026bb003a25c34186aae1f9ac7e95232c38aa31e9561d80fc3aab6edcdf0e6c6d8c5872bc090f23a7a964f009ba71200176d08b4d0eab652261

test:
  secret_key_base: 8e6175bfc5ee11daa7fc3ebc3a52bf8ac5affa125505e94fcfa354e681df25942ad49d20de99024cf13aaf125bc9708f34479622f9672730d29bea995da270f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
